### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by Lewiscowles1986** [hermanhermitage/videocoreiv#10]
Hello :smile: 

Does anyone know how to / if it's possible to have a simple hello-world bootloader for the raspberry pi in ASM?

I was shocked enough to find that the rPi bootcode.bin is run on the videocore chip

**Comment by christinaa** [comment]
Yeah there's an VPU/ARM bootloader that can replace bootcode.bin here: https://github.com/christinaa/rpi-open-firmware

It's not currently being actively developed but it does work and should provide more than a simple "hello world" example. If you're looking for very simple stuff that doesn't require setting up a full toolchain, you can take a look at this: https://github.com/hermanhermitage/videocoreiv/tree/master/uart02
