### ISSUE TITLE
Not an issue, more of a question...

### ISSUE THREAD

**Issue by dshadowwolf** [hermanhermitage/videocoreiv#12]
You have the ``btest`` opcode as being ``Rd & bit(Ra) == 0`` - if "bit test" is looking to see if the bit is set, then ``Rd & bit(Ra) != 0`` would be the result - 2 & 2 == 2 - 3 & 2 == 2 (3 & 1 == 1) - in no spot does the bit actually being set result in 0. So... is "bit test" (``btest``) testing for a bit being set or the bit being not set ? If not-set, then I can understand the logic, but...

**Comment by dshadowwolf** [comment]
read the docs wrong - feeling stupid now

**Comment by dshadowwolf** [comment]
Reopening... The way you've documented this seems wrong - in places where VC4 deviates from ARM you've got it noted and flagged, but with ``btest`` you have it setting Z on a non-match instead of a match. ARM determines EQ/NE by the Zero flag - EQ is Z set, NE is Z clear. This would indicate that, if ``btest`` is checking for a bit being set (seems logical) then on ``Rd & (1 << Ra) == 0`` Z would be 0 - ie: not set.

So... Looking for clarification or if this is just a mistake in the docs.

**Comment by hermanhermitage** [comment]
Could be a mistake in the docs, but I don't have a RPi set up to check any more.

As written:
001100    btest    rd, ra              Z = rd & bit(ra) == 0                 Bit test.

I think this means if rd & bit(ra) == 0 (ie the bit is clear) then the Z flag is set.  That is correct isnt it?
ie test the bit in ra and if zero set the Z flag

**Comment by dshadowwolf** [comment]
If VC4 matches ARM then no, Z should be clear when there is no match. I do not have an easy way to test, as I do not have a Pi I can use for possibly destructive testing. However I do have a (largely cpmplete) emulator that can run the Pi's bootcode and it gets into a "copy 2GiB of RAM from here to 11,800 bytes earlier" chunk of code if it executes btest as documented, but gets into hardware setup and run otherwise.

**Comment by hermanhermitage** [comment]
"Z should be clear when there is no match", isnt that what is written?
 Z = rd & bit(ra) == 0
ie Z = (rd & bit(ra)) == 0
ie if ((rd & bit(ra)) == 0) Z = 1 else Z = 0;
ie if ((rd & bit(ra)) != 0) Z = 0 else Z = 1;
ie if (rd & bit(ra)) Z = 0 else Z = 1;
ie if bit(ra) is set in rd, then Z = 0 (NE), "the given bit is ne to zero"
ie if bit(ra) is not set in rd then Z = 1 (EQ). "the given bit is eq to zero"

Or am I off base?

**Comment by alexzk1** [comment]
https://en.cppreference.com/w/cpp/language/operator_precedence

comapre precendence for & and ==
I think  u miss ()

**Comment by hermanhermitage** [comment]
Ok, so change to (to clarify all precedence)?
  Z = ((rd & bit(ra)) == 0)

As @alexzk1 points out,  assuming C/C++ precedence rules
  Z = rd & bit(ra) == 0, would be
  Z = (rd & (bit(ra) == 0))
  Z = (rd & 0)
  Z = 0
Which was not the intent of the pseudo code.
Much clearer if parens added.

However I'm not sure that is @dshadowwolf point here.

**Comment by dshadowwolf** [comment]
Okay - yes, with this clarification my point holds and the documentation makes sense.

When I first read the documentation my mind parsed it as Z being set to 1 if the bit was not set - and it still wants to do that for some damned reason. (And I've come across and been playing around with a VC4 emulator that had the same assumption in its code for ``btest``)

Thank you @alexzk1 and @hermanhermitage for your patience in this matter - and with my brain doing stupid things.

**Comment by hermanhermitage** [comment]
As written Z *is set* to 1 if the tested bit is 0, or set to 0 if the bit is 1.

Not saying the doc is right (no pi handy), but it definitely matches other instruction sets this way. And leads to intuitive code sequences:
```
  btest r0, 23                   ; Set Z flag to 0 if bit 23 is 1, set Z flag to 1 if bit 23 is 0
  bne r0_bit_23_is_set     ; if Z flag 0
  beq r0_bit_23_is_reset ; if Z flag 1
```

Also see 

https://github.com/mgottschlag/resim/blob/master/libresim/include/videocore/VideoCoreIVRegisterFile.hpp#L58
```
void setStatus(uint32_t mask, uint32_t value) {
	registers[VC_SR] = (registers[VC_SR] & ~mask) | (mask & value);
}
```
https://github.com/mgottschlag/resim/blob/master/libresim/src/videocore/VideoCoreIVExecute.hpp#L499
```
case OP_BTST:
	registers.setStatus(0x8, (a & (1 << b)) == 0 ? 0xa : 0x0);
	break;
```

Which matches the doc (doesn't necessarily mean the doc is right!) as that 0xa gets masked down to 0x8.

I've added the paren to the instruction description for clarity.

Thanks for all the input.  keep up the good work.

Cheers

**Comment by dshadowwolf** [comment]
Wait one...

You've said you have no hardware - I do, actually... I can test, but... when you wrote the docs you noted where things were different between VC4 and ARM. On ARM a "Branch if Equal" checks the Zero Flag - Equals on ARM is "Zero is Set" - ie: ``Branch if Equal`` is ``Branch if Zero`` - see: [ARM Condition Codes and Flags](https://community.arm.com/processors/b/blog/posts/condition-codes-1-condition-flags-and-codes).

This means that the ``eq`` and ``ne`` condition codes in the document need changed or libresim and your docs notation of ``btest`` needs fixed. Regardless, have a nice day and thank you for the patience.

**Comment by dshadowwolf** [comment]
Note that I actually came across this because of Mr. Gottschlags earlier, somewhat abandoned project "vctools", which includes an incomplete VC4 emulator. His code appears to be based on your documentation, so if one is wrong, the other likely is as well.

**Comment by hermanhermitage** [comment]
> On ARM a "Branch if Equal" checks the Zero Flag - Equals on ARM is "Zero is Set" - ie: `Branch if Equal` is `Branch if Zero` - see: [ARM Condition Codes and Flags](https://community.arm.com/processors/b/blog/posts/condition-codes-1-condition-flags-and-codes).

The situation is as I understand it identical on the VC4.

The Z flag is generally set when the result of a ALU operation (that modifies the Z flag) is zero, meaning the last operation produced a zero result.  And its generally cleared (0) when the result of the operation was non zero.

> This means that the `eq` and `ne` condition codes in the document need changed or libresim and your docs notation of `btest` needs fixed. Regardless, have a nice day and thank you for the patience.

The 'eq' and 'ne' condition codes should be identical to ARM.  Only the carry flag ones are likely to be different because the ARM brought forward some 6502isms relating to carry flag, that is not common to most instruction set architectures.

The easiest thing to do would be run this sample code:
```
  mov r0, 8
  btest r0, 3 
    ; Z = ((8 & (1<<3)) == 0),
    ; ie Z = (1 == 0), ie Z = 0,
    ; ie non zero result because bit 3 is set.
    ; ie the Z flag is clear because the result of the bit test was non zero 
    ; and a set Z flag would mean the result of the bit test was zero.
  bne pass
  beq fail
```

**Comment by dshadowwolf** [comment]
will do - my Pi is, apparently, broken so I'm going to have to pass this on to a friend who has a couple that are set aside for this kind of testing

**Comment by dshadowwolf** [comment]
Finally got a test run - result is 0x2000000A for:
```
        mov r1, 8
        btest r1, 2
```
and I get 0x20000000 for:
```
        mov r1, 8
        btest r1, 3
```

This does show that ``btest`` operates in a manner consistent with some older processors but not in the same manner as would be expected from, say, ``cmp``.  Thanks for the patience and giving me a task like this that proves the documentation

**Comment by hermanhermitage** [comment]
Great work. 

I think CMP tends to be a different case as it acts as a dummy subtract with flag capture, setting the flags with a "sense" of the comparison in mind.  Where as btest is not a comparison but a dummy logical-and with a mask of 1<<rd.  So the way to think of btest is afterwards EQ will be true if the bit was EQual to zero, and NE be the case if the bit was NE to zero.  NOT the case that the masked bit was equal to the provided value (as no value is provided just a bit position).

While you are "there" it might be worth updating your test to try out something else.
I notice the docs say in one place that btest modifies NZVC but in the instruction summary it only has it updating Z.

The way to do that would be run the same btest's but force NZVC to all zero and then again with all ones.  eg. I dont know if btest r1, 31; would set the N flag if r1 has the top bit set for example.

I did have a corpus of tests somewhere which I never got around to adding to the repo, and I dont have the time right now to dig out the Pi and find my work.

I just point this out about the flags because it will impact development of an accurate emulator.

**Comment by dshadowwolf** [comment]
From existing results on a non-match it looks like Z and C get set (0x2000000A - that A is 0b1010 - your docs have it as ``UIS- ---- ---- ---- ---- ---- --cb ZNCV``)... I hope we can ignore that it says it's in Supervisor mode there - this is running as a "bootcode.bin"

On a different note - I'm getting a good chunk of garbage from the mini-uart during its initialization - could this be from activating the transmitter and receiver before initializing and clearing the fifo's ?

**Comment by dshadowwolf** [comment]
And yeah, let me add a test for the N flag on btest, too. (I ask the question about the uart b/c I've been having some issues with getting output at all and a simple routine for running down a string seemed to get stuck, so...)

**Comment by dshadowwolf** [comment]
After a short nap I've gotten the test run with the added test of:
```asm
mov r1, 0xFFFFFFFF
btest r1, 31
```
and have:
```
2000000A
20000000
20000000
```
So no, looks like N does not get set if the high-bit of the value being tested is set. (That's "should fail", "should pass" and "test if ones-complement possible number sets N")

And... thanks for pointing out that test needing done. If you've got any other requests, please let me know. I'm going to see if I can get some "default register values" for the devices that don't have any defaults in the broadcom code dump next. Possibly even initialize the PLL so I can get a bit more precise on the baud-rate selection. (btw, the code in "uart01.s", "uart02.s" and "dumpbootrom.s" generates a baud-rate register value of 19 - that comes out to 120000 baud when run through the equation given in the Broadcom peripherals doc - using 20 comes out a lot closer to 115200 (114285))

**Comment by dshadowwolf** [comment]
@hermanhermitage Was working on the emulator and trying to put together a good emulation of the bcm283x "mini uart" when it hit me that the reason ``btest`` acts differently from ``cmp`` is that it isn't an ``equality``, logically, it's a zero/non-zero - it works, basically, exactly how your docs say - it's result is zero/non-zero - using ``beq`` and ``bne`` is because there is no separate ``bz`` and ``bnz`` pair.
