### ISSUE TITLE
Interrupts support and user mode

### ISSUE THREAD

**Issue by kika123** [hermanhermitage/videocoreiv#9]
Is it possible to enable interrupts and the clock? Is there an MMU somewhere as there is user mode?
What's the clock interrupt number in the table?

**Comment by christinaa** [comment]
>Is it possible to enable interrupts and the clock?
Yes. `ei` enables interrupts, but you need to unmask them in IC for them to arrive.
>Is there an MMU somewhere as there is user mode?
No the VC4 architecture does not have a MMU, only an IOMMU that sits between ARM and AXI. It has secure regions that can only be accessed from VPU kernel (secure) mode. There are 4 of them and they're controlled through SDC registers.
>What's the clock interrupt number in the table?
I don't know what you mean by "clock".

**Comment by hermanhermitage** [comment]
Have you got mailbox interrupt sorted now?

I was looking at header files, I think it should fall out from that (but untested). 8 mask registers so 64 4 bit fields but looks like they only take 0..7 not 0..15. Zero means masked.

There are 2 interrupt source registers, so you can determine the source (ie 64)

Not sure about the force bits.

Strangely start.elf/threadx hooks a single handler (apart from SMP) and dispatches from that, I guess it's a portability thing of threadx to loosen coupling on architectural features.

Couldn't trace the value the interrupt handler was using to index into the TX exception table.

I might try and get interrupts going properly for serial debugger on sat.  But flat out right now


Cheers
>Is it possible to enable interrupts and the clock?
Yes. `ei` enables interrupts, but you need to unmask them in IC for them to arrive.
>Is there an MMU somewhere as there is user mode?
No the VC4 architecture does not have a MMU, only an IOMMU that sits between ARM and AXI. It has secure regions that can only be accessed from VPU kernel (secure) mode. There are 4 of them and they're controlled through SDC registers.
>What's the clock interrupt number in the table?
I don't know what you mean by "clock".


---

**Comment by hermanhermitage** [comment]
Kika123,

I've added the hard interrupts at the end of https://github.com/hermanhermitage/videocoreiv/wiki/VideoCore-IV-Programmers-Manual

The first 4 of 64 are for timers.
